<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }

  	function getpackaging(){
  		$this->db->order_by('id');
  		return $this->db->get('tmstpackaging')->result();
  	}

    function getuom(){
      $this->db->order_by('id');
      return $this->db->get('tmstuom')->result();
    }

    function getsource(){
  		$this->db->order_by('id');
  		return $this->db->get('tmstsource')->result();
  	}

    function getuser(){
      return $this->db->get('user')->result();
    }

    function getconvert(){
      $this->db->order_by('id');
      return $this->db->get('tmstconversion')->result();
    }

    function getitem(){
      $this->db->order_by('id');
      return $this->db->get('tmstitem')->result();
    }

    function getpriceuom(){
      return $this->db->get('priceuom')->result();
    }

}

/* End of file Master.php */
/* Location: ./application/models/Master.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-05-24 18:22:33 */
/* http://harviacode.com */
