<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class PriceUom_model extends CI_Model
{
  public $table = 'priceuom';
  public $id = 'code';
  public $order = 'DESC';
    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('code,desc,uomafter,priceuom');
        $this->datatables->from('priceuom');
        //add this line for join
        //$this->datatables->join('table2', 'tmstitem.field = table2.field');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

}

/* End of file Tmstitem_model.php */
/* Location: ./application/models/Tmstitem_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-15 06:10:35 */
/* http://harviacode.com */
