<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tmstpricelist_model extends CI_Model
{

    public $table = 'tmstpricelist';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('tmstpricelist.id as id,tmstitem.desc as iditem,tmstpackaging.packaging,tmstuom.uom,size,price,tmstsource.source');
        $this->datatables->from('tmstpricelist');
        //add this line for join
        //$this->datatables->join('table2', 'tmstpricelist.field = table2.field');
        $this->datatables->join('tmstpackaging', 'tmstpricelist.packaging = tmstpackaging.id');
        $this->datatables->join('tmstuom', 'tmstpricelist.uom = tmstuom.id');
        $this->datatables->join('tmstsource', 'tmstpricelist.uom = tmstsource.id');
        $this->datatables->join('tmstitem', 'tmstpricelist.uom = tmstitem.id');
        $this->datatables->add_column('action', anchor(site_url('tmstpricelist/read/$1'),'Read')." | ".anchor(site_url('tmstpricelist/update/$1'),'Update')." | ".anchor(site_url('tmstpricelist/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('iditem', $q);
	$this->db->or_like('packaging', $q);
	$this->db->or_like('uom', $q);
	$this->db->or_like('size', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('source', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('iditem', $q);
	$this->db->or_like('packaging', $q);
	$this->db->or_like('uom', $q);
	$this->db->or_like('size', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('source', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tmstpricelist_model.php */
/* Location: ./application/models/Tmstpricelist_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-15 06:10:36 */
/* http://harviacode.com */
